### ISSUE TITLE
Problem displaying the 'Detailed alert info'

### ISSUE THREAD

**Issue by Paul-Vdp** [redstone99/hass-alert2-ui#1]
The card displays the Alert2 alerts fine, but no amount of clicking on one of them results in anything, let alone showing its 'Detailed alert info'. It will let me 'Ack' the alert though ...

**Comment by redstone99** [comment]
Hi Paul, I'm guessing this is due to a difference between browsers / OS that I didn't test.
Are you seeing this in the HA app or web browser?
If the app, can you tell me the app version and phone OS?
If the web, can you tell me what browser and version you're running on, and your OS?

I use Firefox 131.0.3 and Chrome 130.0.6723.58 on Ubuntu 24.04, and run the HomeAssistant app 2024.9.4-full on Android 14.

**Comment by Paul-Vdp** [comment]
Hi Josh, sure thing. I have it on both the app (also 2024.9.4-full, but on Android 12) and Chrome (130.0.6723.59 on Win11)
Hope this helps ...
Btw, clicking the alert entity itself DOES open the details view ...
Btw2, hovering over the alert the pointer changes to the 'pointing hand', indicative of a clickable link

**Comment by redstone99** [comment]
Thanks for the extra info. I found the problem - the current code depends on a package "card-tools", which isn't included. I'm recoding to remove the dependency.

**Comment by redstone99** [comment]
I just released v1.1.2 which I believe will fix the issue. @Paul-Vdp , can you give it a try?

Note that after upgrading this package, you may need to clear cookies & site data, or just reload the web page a few times to get alert2.js to update.  The README and release notes have details on how to speed up the update on the Android HA companion app.

**Comment by Paul-Vdp** [comment]
Hi Josh, I tested it on Chrome and all seems well. Couldn't test the app yet for lack of an active alert, but I'm confident it will work as well. Thanks a lot for a quick and perfect fix - as usual ;-)

**Comment by redstone99** [comment]
Great, glad it worked. I'm closing this. Feel free to reopen or file anew if it doesn't work on your phone.
J
