### ISSUE TITLE
Bizarre display

### ISSUE THREAD

**Issue by Paul-Vdp** [redstone99/hass-alert2-ui#2]
Now and then I find the UI display has gone a bit haywire.
And no, no amount of browser cache clearing helps ...
![alert2](https://github.com/user-attachments/assets/22473f34-a42f-4de4-82f4-8f5eb1a1470c)

**Comment by redstone99** [comment]
Confirmed. Thanks for the screenshot.

**Comment by redstone99** [comment]
@Paul-Vdp , I just released v1.1.3 that should fix this formatting issue. Can you give it a try and let me know if it works for you?

**Comment by Paul-Vdp** [comment]
@redstone99 
Hi Josh,
Installed it, everything looks normal. Cannot yet vouch for it to be solved though, because as I said : it only goes haywire now and then - and before installation of the new version it had already gone back to normal.
But hey, I'm confident you nailed it - as usual ;-)
Thanks, mate !

**Comment by Paul-Vdp** [comment]
@redstone99  Hi Josh. Sorry to say so, but I spoke too soon. Just noticed it is back ...

**Comment by redstone99** [comment]
Darn. Ok, a few questions:
- Does it look the same as the previous screenshot you posted?
- what browser are you using?
- can you open the console, and look for a message like " alert2 v1.16" or some other version number and tell me what message you see?  You can view the console on Firefox or Chrome by pressing Shift+Ctrl+I  and maybe clicking on the "console" tab.

The issue I believe is triggered when the width of the card gets narrow. You may be able to reproduce by shrinking your browser window so the card columns get narrow.

Here's what I see when I make a column narrow:

<img src="https://github.com/user-attachments/assets/d822b53c-25c4-40f8-813f-1ce8dd618dd2" alt="drawing" width="400"/>

**Comment by Paul-Vdp** [comment]
It indeed looked exactly the same.
Chrome version 130.0.6723.117 on Win11 laptop.
Console shows alert2 v1.7

I can indeed trigger the effect by shrinking the browser window. However: I have my browser 99.99% of the time on fullscreen, so it seems that for one or other reason the browser and/or the UI prog sometimes gets mixed up and thinks it has to shrink the card's display ? Cannot say I see this happening with any other card though ...

**Comment by redstone99** [comment]
Hi - the "alert2 v1.7" message means your browser loaded the old alert2-ui v1.1.2, not the new v1.1.3 with the fix.
Browsers typically cache Lovelace card code such as alert2.js.  Can you try clearing your cache for the site?
That should pick up the new alert-ui that you updated to.  Then you should see "alert2 v1.16" in your console.

I'll make a change so it's easier to verify the alert2-ui version without going into the console.

**Comment by Paul-Vdp** [comment]
Hi Josh, I could have sworn that I did clear the cache (I always do), but it seems I would have lied then. Cleared the cache and then it showed the correct js version. I'll keep an eye on it, but I assume we're good. Thanks and sorry for unnecessary crying wolf !

**Comment by redstone99** [comment]
No worries.  I'll leave this open a few days in case in case the fix doesn't work for you for some reason.
J

**Comment by Paul-Vdp** [comment]
Not that I keep a constant watch on it, but I haven't seen it appear since updating.
So I guess we can close the issue.
